_documentation/troubleshooting-apps.md
Thanks Mr. Dollar for the help. So nobody bothers you again about it.
=> Add Waiting for App hang to troubleshooting docs

_getting_started/getting-started-with-convox.md
This may seem like a small nit, and that's because it is. That out of the way - I personally don't like it when people tell me to go make a sandwich :P
=> invite user to make a sandwich instead of commanding them

_getting_started/getting-started-with-convox.md, index.md
@mattmanning this seems to come up on Slack a bit.
I'll add some more comprehensive details about regions once the non-lambda region stuff hits core.
I'm not super sold on this being in a callout.. open to suggestions for adjustment.
=> add note about regions supported

_getting_started/environment-variables.md
documenting a helpful tip @ddollar gave me in Slack!
=> suggest promoting after changing environment variables

_getting_started/deploying-an-application.md
changes to reflect the recent cli changes
=> tweaks for cli changes

_documentation/one-off-runs.md
=> document one off runs

_getting_started/developing-locally.md
heavily edited first draft. time to take in some feedback.
its a bit late so will need to follow up with at least one more round
of editing.
=> [wip] document local development

Dockerfile, Procfile, docker-compose.yml
note: this is currenlty failing becuse one needs a
*javascript runtime*.
=> add files to make this convox start-able

_documentation/rack-update-process.md
=> rack update doc

_services/mysql.md
Signed-off-by: Dave Henderson <dhenderson@gmail.com>
=> Fixing typo in MySQL service docs

_services/webhooks.md
documents the http webhook service
=> document http web hooks

_languages_and_frameworks/arbitrary-language-support.md, _languages_and_frameworks/other-languages.md
High-level guide for supporting any language on Convox. This specifically deals with the `Dockerfile` and building the correct image. A subsequent article will cover writing the `docker-compose.yml` to execute commands, connect ports, sync volumes, and link containers.
=> Language support guide

Dockerfile, docker-compose.yml
need ye old javascript runtime
=> works with convox start

_posts/2016-01-21-rack-0.8.md
To preview pull the branch and run `jekyll serve`. Then visit http://localhost:4000.
=> Rack 0.8 blog post

_documentation/links.md
updates docs to reflect more env vars, relaxed linking
gives more examples
=> update docs and give more examples

_languages_and_frameworks/getting-started-with-rails.md
The services syntax is wrong in the Rails Getting Started example
=> fix services syntax in rails example

_documentation/custom-domains.md
The output Convox shows me has the form shown above, doing GH PR in case docs need updating.
=> Custom Domains: update 'Hostname' to 'Endpoints'

_documentation/scaling-rack.md, _documentation/updating-convox.md
Motivated by https://github.com/convox/rack/issues/311
=> more docs around expectations during instance replacement

_config.yml, _layouts/base.html, _layouts/jobs.html, assets/css/convox.css, jobs/index.md, jobs/solutions-engineer.md, jobs/systems-engineer.md
http://site-staging.convox.com/
=> update styles on jobs page

_includes/post.html, _includes/subnav-blog.html, _layouts/blog.html, _layouts/post.html, assets/css/convox.css, blog/index.html
=> make the blog layout more narrow

_deployment/creating-an-app.md
Not sure if the description here is accurate, but here's a stab at some better documentation for https://github.com/convox/rack/issues/633
=> add a section for creating an application

_services/redis.md
I don't think the former does anything? I could be wrong though.
=> update convox env despcription

.dockerignore, _config.yml, _includes/subnav-privacy.html, _layouts/privacy.html, privacy/index.md
=> Privacy Policy

_development/running-locally.md
Adds sections to the Running Locally doc explaining code sync and how to persist data in database containers.
=> code sync and data persistence

team/index.html
=> show more contributors

_posts/2015-08-12-integration-over-invention.md
Fixes broken markdown.
Before:
After:
=> fix formatting in Integration over Invention post

_posts/2015-07-27-open-source.md, _posts/2015-11-20-introducing-grid.md, assets/css/convox.css
Removes right-justification to improve readability.
Before:
After:
=> Blog formatting

_monitoring/notifications.md
=> fixed typo

_reference/cli.md
=> CLI reference section

_deployment/load-balancers.md
=> Document an apps security group parameter

_posts/2016-06-21-easier-ssl-and-free-certs.md
=> SSL blog post

_posts/2016-02-23-private-networking.md
=> yes to Yes

_management/scaling.md
=> Add count -1/0 docs

_posts/2016-06-24-dockercon-2016.md
=> Dockercon Recap post

_deployment/installing-a-rack.md, _reference/supported-aws-regions.md
=> List of currently supported regions

_introduction/getting-started.md
=> reorder guide to put emphasis on developing/verifying with convox start first

_deployment/volumes.md
Doc explaining volume mounting. Should be released at the same time as Rack EFS integration.
I tried to keep this short and sweet like the other docs and show a clear example, but open to suggestions for more.
=> Volumes doc

_config/nginx.conf, _management/private-networking.md
=> Private networking doc

_config.yml, _includes/contact.html, _includes/subnav-cost.html, _layouts/base.html, assets/css/convox.css, cost/index.md, index.html
=> add cost page

_languages/django.md
=> Add Python (Django) docs

cost/index.md
=> tweak support language

_languages/wordpress.md
=> WordPress doc

_console/support-plans.md, _help/support.md
=> describe console support plans

_reference/docker-compose-file.md
=> Add Docker Compose File doc

_management/updating-old-apps.md
Specify the version in which the configuration changed.
Thanks @mwarkentin and @MiguelMoll for the suggestion.
=> include rack version where balancer config changed

_management/environment.md
=> Revisit environment doc

_management/rolling-back.md
=> rollback doc

_posts/2016-07-28-auditing.md
=> audit log blog

_development/preparing-an-application.md
=> Clarify port usage in Preparing an Application doc

_reference/hipaa-compliance.md
=> Add HIPAA Compliance doc

_reference/docker-compose-file.md
=> add convox.idle.timeout to list of labels

_posts/2016-08-12-support.md, assets/css/convox.css, index.html
Blog post with a couple CSS tweaks thrown in.
=> Support Plan Blog Post

_config.yml, _posts/2015-05-18-modern-twelve-factor-apps-with-docker.md, _posts/2015-06-23-a-tale-of-two-onboardings.md, _posts/2015-07-21-zero-configuration-rails.md, _posts/2015-07-27-open-source.md, _posts/2015-08-12-integration-over-invention.md, _posts/2015-08-18-convox-0.5.md, _posts/2015-10-08-rack-0.6.md, _posts/2015-10-19-rack-0.7.md, _posts/2015-11-20-introducing-grid.md, _posts/2016-01-21-rack-0.8.md, _posts/2016-02-03-ecr.md, _posts/2016-02-23-private-networking.md, _posts/2016-04-09-build-refactor.md, _posts/2016-04-21-scheduled-tasks.md, _posts/2016-04-27-ecs-challenges.md, _posts/2016-05-23-open-source-evolution.md, _posts/2016-06-16-bidirectional-sync.md, _posts/2016-06-21-easier-ssl-and-free-certs.md, _posts/2016-06-24-dockercon-2016.md, _posts/2016-06-30-why-docker.md, _posts/2016-07-07-efs.md, _posts/2016-07-28-auditing.md, _posts/2016-08-11-services-over-software.md, _posts/2016-08-12-support.md, _posts/2016-08-14-alb.md
=> blog excerpts

_services/sqs.md
`database` -> `queue` when referring to SQS.
=> Fix small typo

cases/opendoor.md, index.html
=> Opendoor case study

_deployment/load-balancers.md
=> adding load balacer health check docs

_posts/2016-08-18-rack-auth-postmortem.md
I'm happy to hear more feedback about the incident on this PR before publishing this postmortem...
=> rack auth postmortem blog post

_config.yml, _integrations/circle-ci.md, _integrations/github.md, _integrations/gitlab.md, _integrations/slack.md, _integrations/travis-ci.md
=> Add integrations docs: CircleCI & Travis CI

_management/api-keys.md
=> console and rack API key reference

_reference/iam-policy.md
=> IAM install policy

_layouts/docs.html, assets/css/convox.css
Links go to issue creation and pull request creation.
=> Add links for submitting feedback

_reference/supported-aws-regions.md
=> List AWS regions added in release 20160813014741

_management/internal-apps.md
=> Internal apps / rack doc

_deployment/scheduled-tasks.md
Should be deployed consecutively with https://github.com/convox/rack/pull/1156
=> cron task names can have dashes

_reference/docker-compose-file.md, _reference/docker-compose-labels.md
=> Add Docker Compose Labels doc

_deployment/installing-a-rack.md
=> Add VPC instructions to Installing a Rack doc

_reference/docker-compose-file.md
=> Warn about underscored names in Docker Compose doc

_management/scaling.md
=> Mention autoscale log filtering in the scaling doc

_reference/docker-compose-file.md
=> Clarify build config in Docker Compose File doc

Dockerfile, _config/nginx.conf, docker-compose.yml
=> use convox/jekyll base image

_reference/rack-parameters.md
=> Add Rack Parameters doc

_deployment/rolling-updates.md
=> Rolling Updates Doc covers config

_reference/iam-policy.md
=> Clarify policy link in IAM Policy doc

_reference/app-parameters.md
=> Add App Parameters Doc

_deployment/installing-a-rack.md, _deployment/vpc-configurations.md, assets/css/convox.css
=> Add VPC Configurations doc

_deployment/scheduled-tasks.md
=> Explain cron start time skew

_deployment/builds.md
Explains what builds are and how they work.
Includes info about build export/import.
=> Builds doc

_includes/post.html, _posts/2016-09-20-three-generations-of-aws.md, assets/css/convox.css
=> Three Generations of AWS blog post and style tweaks

_reference/iam-policy.md
=> add kms permission

_reference/cli.md
=> Typo fix in _reference/cli.md (overridded -> overriden)

_deployment/builds.md, _management/one-off-processes.md
=> Doc updates for Rack 20160928105531

.dockerignore
=> add .git to dockerignore

.dockerignore
=> add .env to dockerignore.

_integrations/circle-ci.md
=> Rename name of tab with user / service listing

team/index.html
=> clean up team page

_services/postgresql.md
=> Document postgres --version option

_integrations/circle-ci.md, _integrations/travis-ci.md, _management/api-keys.md, _management/logs.md, _management/one-off-processes.md, _management/scaling.md, _management/updating-old-apps.md, _monitoring/monitoring-an-app.md, _monitoring/notifications.md
=> Docs Review, part 2

_layouts/guide.html
=> open feedback against guide

_posts/2016-10-18-the-convox-guide.md
=> Guide blog post

_reference/rack-parameters.md
=> Indicate units for disk size.

_reference/docker-compose-file.md
=> Fix networks link in Docker Compose File doc

_posts/2016-10-19-botmetrics-enterprise-grade-deployment-on-aws.md
=> Botmetrics blog post

_posts/2016-10-19-botmetrics-enterprise-grade-deployment-on-aws.md, _reference/cli.md, assets/css/convox.css
Plus tweaks for the Botmetrics blog post and reverting the sticky header.
=> .convox/app

_guide/10-databases.md
=> Databases guide copy fixes

_includes/segment.html, _layouts/blog.html, _layouts/post.html, assets/css/convox.css, blog/index.html
=> Blog sidebar

assets/css/convox.css
=> Make blog index more responsive

_console/workflows.md, assets/css/convox.css
=> Update workflows doc

team/index.html
=> Add AJ to team page.

_guide/15-deploy.md
=> deployment guide start; link to existing docs and summarize steps

_guide/01-introduction.md, index.html
This depends on https://github.com/convox/site/pull/296 or similar to land, so the guide doesn't abruptly end before rack setup and deploy.
=> Homepage Getting Started -> Guide

_reference/docker-compose-file.md
=> Add mem_limit and cpu_shares to Compose file documentation.

_includes/nav.html
=> login -> signup

_reference/supported-aws-regions.md
=> support for us-east-2 region

_includes/mailchimp.html
=> fix subscription created virtual page

_reference/app-parameters.md
=> Fix link to "Internal Apps doc" on "App Parameters" page

_posts/2016-10-19-botmetrics-enterprise-grade-deployment-on-aws.md, _posts/2016-11-07-encryption-at-rest.md
=> Encryption At Rest Blog

_reference/rack-parameters.md
=> Document BuildMemory rack param

_posts/2016-11-11-docker-in-production.md
=> docker in production

_services/syslog.md
New behavior for using syslog service within a VPC.
Related: https://github.com/convox/rack/pull/1381
=> new syslog changes

index.html
=> reenable product video; tweak CTA tracking

assets/css/convox.css, index.html, team/index.html
* Tune header to make signing up only CTA
* Add product section that demonstrates team workflow
* Move logos / quotes closer to the fold
* Small layout and responsiveness tweaks
=> Emphasize Team Features

assets/css/convox.css, index.html
=> add product links

jobs/index.md
=> Add Kansas City to distributed team locations.

_services/postgresql.md
=> Add --database parameter

_development/installation.md, _reference/cli.md
=> Update autocompletion and PS1, especially for Linux users.

_guide/17-app.md, _guide/18-releases.md
=> Add definitions to app and release Guide pages.

_guide/18-releases.md
=> Add 'further reading' links to Releases Guide page.

_config.yml
=> Remove version number from Guide.

_development/installation.md
=> Add homebrew installation instructions and linkify /docs/installation.

_includes/process-to-service.md, _includes/service-to-resource.md
=> Comment out link to definition page.

_development/running-locally.md
=> Add 'Environment' section to 'running locally' doc. Resolves #182.

_config/nginx.conf, _development/preparing-an-application.md, _layouts/base.html, _posts/2015-05-18-modern-twelve-factor-apps-with-docker.md, _posts/2015-10-08-rack-0.6.md, _posts/2016-10-19-botmetrics-enterprise-grade-deployment-on-aws.md, cases/opendoor.md, team/index.html
Check entire site with a 404-finder tool, update all broken links.
Note: There's a lot of links to `grid.convox.com`; I'm not sure what to do about those.
Also, there's a ton of broken links in the blog posts.
=> Check links

_reference/rack-parameters.md
=> Add missing Rack parameters.

_includes/nav.html, _posts/2016-10-19-botmetrics-enterprise-grade-deployment-on-aws.md, assets/css/convox.css, reinvent/index.html
/reinvent landing page for the URL on the print flyers.
=> Reinvent Landing Page

pci/index.html
First cut. Future enhancements would be logos, quotes, white paper.
=> pci landing page

_bin/web, _layouts/base.html, docker-compose.yml
=> Don't load Google Analytics, Facebook, Intercom etc in development mode.

_reference/rack-parameters.md
=> fixed min InstanceCount

_posts/2016-12-05-codebuild.md
=> CodeBuild blog post

_posts/2016-12-05-codebuild.md
=> add subtitle and summary marker

_management/scaling.md
I didn't find how to scale cpu until I asked via Slack.  Would be nice to be in the docs!
Thanks,
Ryan
=> Add scaling cpu to scaling docs

_includes/definitions/changes/service-to-resource.md
=> Change 'will happen very soon' to 'has happened'.

_management/environment.md
=> Environment scope

_config.yml, _heroku/01-introduction.md, _heroku/02-docker.md, _layouts/heroku.html, _posts/2016-12-13-heroku-to-convox-guide.md, assets/css/convox.css
=> Heroku to Convox Guide

_reference/login-and-authentication.md
=> Login docs

_deployment/vpc-configurations.md
Update for the changes in https://github.com/convox/rack/pull/1439.
Specify that an Internet Gateway ID must be passed.
=> update instructions for installing into an existing VPC

_development/running-locally.md, _reference/docker-compose-labels.md
=> Add '--shift' documentation.

_posts/2016-12-15-efs-good-bad-ugly.md, _posts/2016-12-16-challenges-of-efs.md
=> efs benchmark blog post

_posts/2016-12-16-challenges-of-efs.md
=> links and typos

_console/integrations.md
This PR adds a new doc for Console integrations. It explains the issues around private forks.
=> Integrations doc

_deployment/scheduled-tasks.md
Add an example that uses comma syntax to show how one can use it in scheduled tasks.
=> Add Comma-Syntax Example to Scheduled Tasks (docs)

_config/nginx.conf, _management/api-keyroll.md, _management/api-keys.md, _management/debugging.md, _reference/cli-config-files.md, _reference/login-and-authentication.md
=> Fix broken links to /docs/keyroll.md. Add additional info about Rack API keys.

_includes/nav.html
=> remove automation and team from nav

_development/running-locally.md
=> Document --no-build option

_development/linking.md
=> fixed a markdown formatting issue

_management/scaling.md
=> Demonstrate convox scale to query current scaling

_management/api-keyroll.md
=> Reword Rack API keyroll section.

_posts/2017-01-06-migrating-to-the-new-lambda-runtime.md
=> Lambda runtime migration blog post

_resources/about-resources.md, _resources/sqs.md
=> Clarify SQS resource public internet visibility

_management/scaling.md
=> Document minimum Rack instance count of 3

_deployment/deploying-to-convox.md
=> Document `convox apps cancel`

_console/workflows.md, assets/css/convox.css
Usage:
`![](/path/to/image.png) *Caption; must go on the same line as the image.*`
The caption will appear below the image, centered, slightly smaller and lighter than the surrounding text:
Inspiration: [StackOverflow](http://stackoverflow.com/a/30366422/1991403)
=> Add 'img + em' CSS class to convox.css to facilitate image captions.

_resources/about-resources.md
=> Add instructions for 'convox resources update'.

_integrations/travis-ci.md
* include Convox CLI install step
* refer to Rack API key instead of password
* link to API keyroll doc
* include AWS CLI command to retrieve Rack hostname.
Resolves #434
=> Update Travis CI install instructions

_development/running-locally.md
=> specify that other port labels will be shifted

_reference/cli-environment-variables.md
=> Document CONVOX_WAIT

_reference/rack-parameters.md
=> Add search-friendly tip for increasing ContainerDisk parameter.

_guide/19-resources.md
=> Update one last 'service' to 'resource'

_deployment/volumes.md
=> Document how to delete rack volumes

_deployment/load-balancers.md
=> add note about internal/external ports conflict

_config/nginx.conf
=> Use 'return 301' instead of 'rewrite 301' in nginx.conf.

_reference/supported-aws-regions.md
=> us-west-1 is now supported

_console/aws-integration.md, _management/api-keyroll.md, _management/api-keys.md, _reference/aws-integration.md
=> New Onboarding Docs

_includes/mailchimp.html, _includes/segment.html, _layouts/base.html
=> Fix subscribe form

Makefile, _bin/test
=> Add script to test site for broken links; run with 'make test'

_console/aws-integration.md
=> Add sample CSV format to AWS integration page.

_includes/mailchimp.html, assets/css/formed.css
=> Restyle oversized mailchimp form on blog

_includes/post.html, assets/css/formed.css
=> Site redesign tweaks

_config/nginx.conf
=> Redirect /docs/creating-an-iam-user

_reference/app-parameters.md
=> Add SecurityGroup app param

_guide/19-resources.md, _includes/definitions/changes/service-to-resource.md, _languages/wordpress.md, _management/updating-old-apps.md, _monitoring/notifications.md, _resources/memcached.md, _resources/mysql.md, _resources/postgresql.md, _resources/redis.md, _resources/s3.md, _resources/sqs.md, _resources/syslog.md, _resources/webhooks.md
=> Improve resources docs

_resources/sqs.md
=> Add missing SQS resource creation options

_resources/sns.md
=> Add SNS doc

_deployment/load-balancers.md, _deployment/port-mapping.md
+ Surround example port pairs in quotations as per recommended practice.
=> Specify that ports on the same service should be either external or internal

_management/scaling.md
=> Add autoscaling details to /docs/scaling

_reference/rack-parameters.md
=> Add example to InstanceBootCommand Rack param.

_development/convox-proxy.md
=> Add nonstandard port tip to 'convox resources proxy' doc.

_development/linking.md, _guide/06-environment.md, _guide/11-links.md, _management/environment.md
=> Interlink environment and linking documentation and guide pages.

_posts/2017-01-26-new-region-us-east-2.md
**Important:** `us-west-1` isn't in the dropdown on the Console rack install screen. Hold off on publishing until it is.
=> us-west-1 blog post

_posts/2017-01-30-new-region-us-west-1.md
=> Unpublish and rename file of blog post about us-west-1.

_deployment/ssl.md
=> Add note about wildcard certs not covering the bare domain.

_guide/01-introduction.md, _includes/overview.md, _introduction/getting-started.md
The Console setup checklist offers the simplest way to get everything set up. This brings docs closer in line with following that checklist:
- Create an organization
- Connect an AWS account
- Launch a production-ready cluster
- Connect the Convox CLI
=> Update Getting Started for new Web Onboarding Flow

_posts/2017-01-30-new-region-us-west-1.md
=> Set published to true on us-west-1 post

_management/instance-rolls.md
=> Add Instance Rolls doc

_resources/mysql.md, _resources/postgresql.md, _resources/redis.md
=> Add missing options to resources docs

_reference/security.md
This PR adds a new doc that explains the KernelUser permissions lockdown effort as well as some other security benefits of using Convox.
=> security doc

_integrations/datadog.md, _management/scaling.md, _reference/rack-parameters.md
=> Update docs to reflect default autoscaling.

_posts/2017-02-02-aws-integration.md
=> aws integration blog post

_deployment/port-mapping.md, _reference/docker-compose-labels.md
First draft. Might benefit from added emphasis or warning blocks or something.
=> [WIP] UDP support + `convox.balancer` 

_deployment/volumes.md
Reverts convox/site#494
Needed rebase.
=> Revert "update volumes doc"

_development/installation.md, _introduction/getting-started.md
A couple of changes I failed to push into https://github.com/convox/site/pull/493 before merging
=> more onboarding changes

_reference/cli-environment-variables.md
=> Document CONVOX_RACK environment variable.

_reference/cli-environment-variables.md
=> Document CONVOX_RACK, CONVOX_PASSWORD env var

_reference/docker-compose-file.md
New behavior added by https://github.com/convox/rack/pull/1656
=> Document empty environment variables in docker-compose.yml.

_includes/footer.html
This is how I like to do it, so there won't be any need to touch this ever again.
=> fix wrong year in footer once and forever

_deployment/builds.md, _development/preparing-an-application.md, _reference/dockerfile.md
Inspired by https://github.com/convox/rack/pull/1666
=> Document build args

assets/css/convox.css
=> Tweak monospace formatting

_reference/security.md
=> Fix typos in _reference/security.md

_reference/app-parameters.md
=> Document TaskRole app parameter

_management/environment.md
=> Document 'env set --id'

_posts/2016-04-27-ecs-challenges.md, _posts/2016-06-30-why-docker.md, _posts/2016-07-07-efs.md, _posts/2016-07-28-auditing.md, _posts/2016-08-12-support.md, _posts/2016-08-14-alb.md, _posts/2016-10-19-botmetrics-enterprise-grade-deployment-on-aws.md, _posts/2016-12-05-codebuild.md, _posts/2016-12-16-challenges-of-efs.md, _posts/2016-12-20-windows.md
I verified these links are all good by
```
$ egrep -ho 'https://cdn-images-1.medium.com/[^)]+' *.md | xargs curl -I --silent | grep HTTP
HTTP/1.1 200 OK
HTTP/1.1 200 OK
HTTP/1.1 200 OK
HTTP/1.1 200 OK
HTTP/1.1 200 OK
HTTP/1.1 200 OK
HTTP/1.1 200 OK
HTTP/1.1 200 OK
HTTP/1.1 200 OK
HTTP/1.1 200 OK
HTTP/1.1 200 OK
HTTP/1.1 200 OK
HTTP/1.1 200 OK
HTTP/1.1 200 OK
HTTP/1.1 200 OK
HTTP/1.1 200 OK
HTTP/1.1 200 OK
HTTP/1.1 200 OK
HTTP/1.1 200 OK
HTTP/1.1 200 OK
HTTP/1.1 200 OK
HTTP/1.1 200 OK
HTTP/1.1 200 OK
HTTP/1.1 200 OK
HTTP/1.1 200 OK
HTTP/1.1 200 OK
HTTP/1.1 200 OK
HTTP/1.1 200 OK
HTTP/1.1 200 OK
HTTP/1.1 200 OK
HTTP/1.1 200 OK
HTTP/1.1 200 OK
HTTP/1.1 200 OK
```
=> update medium image locations

_reference/rack-statuses.md
=> Add Rack Statuses doc

_management/one-off-commands.md, _monitoring/monitoring-an-app.md, assets/css/convox.css
=> Style warnings and callouts differently

_reference/cli.md
=> Use urfave/cli URLs

_deployment/rolling-updates.md, _management/ssh-keyroll.md, _reference/rack-statuses.md
* remove ssh keyroll unavailability info
* mention instance draining
* interlink with rack statuses doc
=> Document instance draining

_management/advanced-build-options.md
=> build options docs

_deployment/installing-a-rack.md, _reference/advanced-installer-options.md
=> Create separate doc for advanced rack installer options

_deployment/vpc-configurations.md
=> Replace CLI instructions for installing Racks into existing VPCs with Console instructions

_reference/docker-compose-labels.md
=> Document convox.draining.timeout label

_reference/app-statuses.md
=> Add App Statuses doc

_reference/convox-roadmap.md
=> Document the Convox Roadmap

_reference/docker-ignore-file.md
=> Document the .dockerignore file

pricing/index.md
=> rework pricing page

_layouts/docs.html, _posts/2017-02-21-buildpacks.md
=> buildpacks blog post

_posts/2017-03-01-new-region-eu-west-2.md, _reference/supported-aws-regions.md
=> Blog post and update regions list for eu-west-2

_reference/command-convox-init.md
=> Add convox init doc

_management/advanced-build-options.md
=> remove section on build artifact caching until that feature lands

_introduction/getting-started.md, _languages/rails.md
=> Update docs to reference new rails example

_console/integrations.md, _integrations/integrations-overview.md
=> Add GitHub oauth scope info

_development/preparing-an-application.md
=> update the preparing an app doc to reflect buildpacks

_deployment/builds.md
=> Document incremental builds

_reference/rack-statuses.md
=> Add CF statuses to docs for searchability

_deployment/volumes.md
=> Document which regions EFS is available in

_reference/cli-environment-variables.md
(`CONVOX_WAIT`, `CONVOX_DEBUG`, `RACK_PRIVATE`)
=> Specify acceptable format for CLI-specific bool envvars

_layouts/heroku.html, _reference/rack-parameters.md
=> Document buildimage

_reference/cli-environment-variables.md
Followup to #632, I missed a slash
=> Replace another slash with a comma

_posts/2016-07-07-efs.md
=> tenet, not tenant

_reference/docker-compose-labels.md
Documentation for https://github.com/convox/rack/pull/1986
=> Document the convox.agent label

_includes/nav.html
=> Login should link to login page, not signup page

_reference/docker-compose-labels.md
=> Add detail about convox.agent.

_management/scaling.md
Granted, there's some repetition of info that's already present elsewhere, but the FAQ format may make it easier to find in some cases.
=> Add autoscaling debugging tips

_reference/rack-parameters.md
As per @MiguelMoll request [here](https://github.com/convox/rack/pull/2040/files#r105666027)
=> Buildimage

_development/linking.md
=> Typo with the postgres scheme for prod example

assets/css/convox.css
Just a quick brush up for the mobile version of the main menu to make things a little prettier and more usable.
=> Center mobile menu items. Delete border shadow.

_deployment/volumes.md
=> Specify that volumes aren't shared across different services

_console/access-control.md
=> update environment permissions

_reference/rack-parameters.md
=> Document HttpProxy Rack param

_console/access-control.md, _console/deploy-keys.md, _integrations/circle-ci.md, _integrations/travis-ci.md, _reference/security.md
=> Update outdated wording on deploy key creation

_reference/rack-parameters.md
=> Document EncryptEbs Rack param

_reference/rack-parameters.md
=> Document InstanceRunCommand and InstanceBootCommand on build instances

_console/workflows.md, _deployment/health-checks.md, _deployment/load-balancers.md, _deployment/rolling-updates.md
=> Move health checks doc to its own section

_management/environment.md
=> Add note about local envvars being overridden by .env/docker-compose.yml

_management/logs.md
=> Document CloudFormation and EC2 Rack and app logs

_reference/cli.md
**Goal:** simplify the documentation, leave Homebrew out of it.
=> Rework the CLI completion documentation

assets/css/convox.css
=> Make docs header white

_posts/2017-03-30-lambda-migration.md
=> lambda migration announcement

_deployment/ssl.md
=> Add cert format tip in ssl doc

_deployment/scheduled-tasks.md
I'm not sure my explanation is very clear; suggestions welcome.
=> Document 'one-off' cron tasks

_deployment/volumes.md
=> Specify that read-only volumes are not currently supported

.convox/rack, .dockerignore
=> Add *.swp to .dockerignore; pin repo to convox/staging rack.

_deployment/volumes.md, _development/convox-proxy.md, _development/running-locally.md, _resources/about-resources.md
=> Add context and interlinking about local volumes and proxying to remote resources

_development/convox-proxy.md
Addressing https://github.com/convox/rack/issues/1928
=> clarify wss proxy tunnel

_reference/aws-instance-types.md, _reference/rack-parameters.md
=> Add page on AWS instance types (+ reserved + spot)

_posts/2017-03-30-lambda-migration.md
=> clarify lambda instructions

_posts/2017-03-30-lambda-migration.md
=> Explain required updates and specify target release version for Lambda upgrade

pricing/index.html
=> Replace basic with free developer plan

_console/support-plans.md, _reference/login-and-authentication.md
=> remove other traces of Basic

_reference/hipaa-compliance.md, enterprise/index.html
=> note about customer references

enterprise/danone.html, enterprise/index.html
=> Danone case study

_management/environment.md, _reference/docker-compose-labels.md
New docs for secure environment functionality.
These link to https://github.com/convox/secure-environment/releases where the latest `secure-environment` build is available and to https://github.com/convox-examples/secure-env-example which has example files and an updated README with more info.
=> secure environment docs

.convox/rack, api/manifest.yml
API doc update for https://github.com/convox/rack/pull/2192
=> API run output

_deployment/private-registries.md
=> clarify ECR is already set up in same account

_introduction/rack.md
=> fix broken image link

_posts/2017-07-25-new-development-platform.md
=> call to action

_reference/aws-instance-types.md, _reference/rack-parameters.md
=> document spot instance and api count params

_config/nginx.conf
=> redirect /guide to getting started docs

_posts/2017-03-30-lambda-migration.md
=> Clarify syslog unlink and link instructions

_languages/rails.md
=> Correct Rails documentation to read Rails rather than Django

_gen2/convox.yml.md
=> Add documentation for internal app flag.

_deployment/health-checks.md, _reference/docker-compose-labels.md
* convox.health.interval
* convox.health.threshold.healthy
* convox.health.threshold.unhealthy
=> Add undocumented convox.health labels

_gen2/convox.yml.md
This PR adds some basic examples for the advanced configuration of build and health checks.
=> Adding advanced build and health examples for convox.yml

_management/rack-updates.md
The advice is mentioned in this comment: https://github.com/convox/rack/issues/2365#issuecomment-349718745
=> Note to redeploy applications after rack update

_gen2/convox.yml.md
Either day or week or day of month must be a question mark.
=> Adjust sample schedule syntax

_gen2/convox.yml.md
due to:
- https://github.com/convox/rack/pull/2350
- https://github.com/convox/rack/pull/2554
=> Multiple domains and scaling through convox.yml

_management/scaling.md
=> tweak docs for service autoscaling

_help/troubleshooting.md
Based on my own trial and error so not at all sure this is 💯, but 🤷‍♂️ it worked for me 😬...
=> Add section for how to run on Fargate

_management/environment.md
=> Make note of the support for shared environment

_gen1/scheduled-tasks.md
=> Use five-part cron syntax

_deployment/custom-domains.md
I get "ERROR: yaml: line #: did not find expected alphabetic or numeric character" when using a wildcard domain. Quoting the string fixed it.
=> fix string format

_reference/convox.yml.md
=> add init to services

_integrations/datadog.md
=> Just fixing the verb typo

_reference/convox.yml.md
=> add memcached reference

_resources/about-resources.md, _resources/memcached.md, _resources/mysql.md, _resources/postgresql.md, _resources/redis.md, _resources/s3.md, _resources/sns.md, _resources/sqs.md, _resources/syslog.md, _resources/webhooks.md
=> fix resource cli syntax

_reference/vpc-configurations.md
As of February 2018, inter-region VPC peering appears to be widely supported: https://aws.amazon.com/about-aws/whats-new/2018/02/inter-region-vpc-peering-is-now-available-in-nine-additional-aws-regions/
=> Update docs with inter-region VPC peering

_posts/2018-11-05-rolling-deploys.md
=> new rolling deploy blog post

_config.yml, _includes/og.html, _layouts/base.html, _posts/2018-10-22-twelve-factor-revisited.md, _posts/2018-11-05-rolling-deploys.md
=> improve SEO and sharing with proper tags

_development/remote-resources.md
```
$ convox -v
20181026182223
```
=> update convox resources proxy note to use --port instead of --listen

_posts/2018-11-29-commit-your-node-modules.md
=> new blog post on committing node modules

pricing/index.html
=> pricing changes
