_getting_started/getting-started-with-convox.md
Adjusting the internal links to the new prefix and fixing a broken markdown link.
=> Fix broken links on Getting Started section

_getting_started/scaling-processes.md
Simple fix about a link in the scaling processes page.
=> Fix link to database in scaling processes page

_documentation/troubleshooting-apps.md
`convox debug` is no longer part of the cli.
This removes references to it in the troubleshooting doc.
=> remove references to defunct debug cli command

_getting_started/scaling-processes.md
Remnant of old cli naming scheme?
Renamed `convox system scale` to `convox rack scale`
=> Rename system to rack for scaling command

_services/postgresql.md, _services/redis.md
There's a transposition error in the current docs `convox services create TYPE NAME` vs `convox services create NAME TYPE`
This builds on @superlogical's patch #38 to apply the same fix to the Redis docs.
=> Fix service ordering

_documentation/port-mapping.md
This is a very technical document. It covers behind the scenes of how CloudFormation, ECS and ELB are configured for port mapping.
It aims to serve as a reference for how port mapping really works, and for commands you can use to describe the current configuration for support purposes.
=> port mapping doc

_config.yml
I broke this on a previous change. Here is a fix.
=> Fix blog permalinks so they have the /blog prefix again

_documentation/ssl.md, _languages_and_frameworks/getting-started-with-rails.md
This adds instructions for doing a Javascript redirect of http requests to https to both the Rails doc and the SSL doc.
=> instructions for javascript redirect

_getting_started/developing-locally.md
To address a question from anton on Slack. The documentation incorrectly talks about a local `convox exec` when this command now only operates on the app running in a rack.
> How does `convox exec` know when to talk to the local docker daemon and when to talk to the rack?
> I am trying to run a one off process locally, and I'm getting this error:
> ```ERROR: InvalidParameterException: Services cannot be empty.
>        status code: 400, request id: baddd3da-d514-11e5-a7bd-b73cc91c108a```
> Incidentally, I get the same error with `convox ps`. This is in an 'undeployed' app that I am trying to test locally first before deploying.
> So I assume my attempt to run `convox exec` is talking to the rack rather than locally, even though I gave it a service name rather than a pid.
> If it matters, …
=> replace local `convox exec` with `docker ps` and `docker exec`

_documentation/uninstall-convox.md
Was missing an explanation of the --region flag for clusters in regions other than default us-east-1 region
=> Added --region flag in uninstall guide

_documentation/updating-convox.md
I think because it was inside of an HTML block, the standard markdown link syntax doesn't work.
Switched to a standard HTML link.
=> Fix link markdown

_services/webhooks.md
Tiny PR. Replaces `(anchor)[URL]` with CommonMark `[anchor](URL)`.
=> Fix RFC 3339 hyperlink markup

_languages/rails.md, _languages/sinatra.md
This should be deployed when https://github.com/convox/rack/pull/657 is released.
=> convox init generates .dockerignore

_includes/subnav-docs.html, _layouts/docs.html
TOC dropdown was unintentionally removed in a layouts cleanup in 4205fc3
=> Add back missing /docs TOC dropdown on mobile

_introduction/getting-started.md
The intended app to be used in this getting started example is Convox's sample Rails app, and identifying that as "your app" is confusing, as it's not actually the user's app that's being used. The language has been amended to make it more clear that the app being referred to is the sample app.
=> Adding clearer language for what app we're using.

_languages/wordpress.md
Because of the move to `AWS::ECS::Service` these directions as written will no longer work. If you try to deploy the app before setting up the database, the service will never stabilize and the deployment will eventually roll back.
This PR changes the order of the steps to set the DB env vars first, so that when you deploy the app for the first time it will start.
=> set WordPress DB env vars before deploying

_management/api-keys.md
Something about the AWS cli commands here causes rack parameters to get reverted, including the instance count and type parameters, which is dangerous. This PR removes those instructions until we can figure out how to safely reset the password via aws cli.
=> remove aws cli password reset steps

.gitmodules, _config.yml, _includes/nav.html, _layouts/docs.html, _layouts/guide.html, assets/css/convox.css
Guide copy has been extracted to https://github.com/convox/guide. Please direct content feedback to that repo.
This PR is for the pieces to import the guide content as a site collection:
* guide content submodule
* site CSS for guide
=> Guide section that uses convox/guide

assets/css/convox.css
The guide's really rad — thanks! — and I thought it might be helpful to make the sidebar sticky, for those of us on really stupid browsers that support it, like Safari (I think Chrome still hides this behind a flag or something).
See:
(Haha, apparently this gif doesn't loop at all, sorry, too lazy to fix it.)
This comes from the department of stupid-shit-I-add-because-eventually-other-browsers-will-support-it-but-in-the-meantime-I-want-it-now. Case in point: I made the GitHub Issues sidebar sticky two years ago and I swear to god someone will notice it as soon as Chrome adds support and I'm not going to get any credit for it anymore and these are the things that keep me up at night.
/cc @nzoschke and co
=> Sticky guide sidebars

_includes/blog-extras.html, _includes/mailchimp.html, _layouts/base.html, _layouts/post.html, assets/css/convox.css, blog/index.html, index.html
One step towards removing aqua buttons. Drop the Slack and Subscribe buttons that link off to another property. Replace with inline signup forms.
=> Contact Form

_development/linking.md
`LINK_PORT` added in https://github.com/convox/rack/pull/1370
=> Add `LINK_PORT` support to linking docs

_includes/algolia.html, assets/css/algolia.css
Here is a PR to add Algolia DocSearch to the website, following your support ticket.
DocSearch is way easier to use than the Jekyll plugin. We actually have a cron that will crawl your website every 24 hours, read the HTML markup, and index it into Algolia. It comes with its own JavaScript library (`docsearch`) that will bind a specific input to display results on each keystrokes. And best of all, it's free and you don't need an Algolia account to use it.
This means that, unfortunatly, all the work you've put into integrating the Jekyll plugin was not needed here. Advantages of DocSearch over the Jekyll plugin is that it's easier to install and maintain, and really tailored for search in technical documentation. The downside is that it's a crawler running every 24h, so if you push a new …
=> Adding Algolia DocSearch

_guide/19-resources.md
Looks like this page doesn't exist anymore. Should the link be removed or updated to something else?
=> remove link to automation page

_integrations/datadog.md
The agent app deploy won't work until https://github.com/convox/rack/pull/1443 lands.
Would love to have a better Autoscale Rack daemon story but that shouldn't get conflated with simple Datadog guidance.
=> datadog agent doc

_reference/docker-compose-file.md
Update mem_limit docs to reflect the fact that mem_limit is interpreted in bytes if no label is provided.
=> Update mem_limit docs

_deployment/volumes.md
Remove inaccurate callout about how volumes with `host:container` declarations work.
Update info about cleaning up persisted files.
=> update volumes doc

assets/js/focus-search-box.js
- Add correct Keycode for QWERTZ  
- Prevent default behavior for keydown
- Remove clean up function
- Add toggle functionality if search field is still empty
- Clean up code
- Refactor code to switch statement
@soulshake I changed some stuff. Hope you like it. Somehow I gave you the wrong keycode (my bad). Cleanup was not working for that keycode, but I think it's much simpler to prevent the default key behavior in the first place so no clean up is needed at all. 
I switched the function to JQuery keydown listener. I think thats more native. I changed the code to a switch statement because it should be faster and is more readable in my personal opinion. Additional keycodes can be added easily.   
Please get rid of the toggle functionality, if you don't like it. I thought it'll be nice to …
=> Refactor to make cleanup function obsolet. Add correct keycode

api/index.html
This is the way it was before; pointing to the site/api/manifest.yml was a temporary measure.
=> Restore link to api manifest.yml on rack repo

api/index.html
This reverts commit 7e237d11de6e5eabfa386f902376cd526f3e8f1b.
Will revert this revert once https://github.com/convox/rack/pull/1922 is in production.
=> Revert "Restore link to api manifest.yml on rack repo"

_deployment/scheduled-tasks.md
Update day of week schedule expression to match AWS:
http://docs.aws.amazon.com/AmazonCloudWatch/latest/events/ScheduledEvents.html
=> Update day of week schedule expression to match AWS

_reference/dockerfile.md
In the existing examples on https://convox.com/docs/dockerfile, we encouraged excluding the development and test Gemfile groups during local builds, which is actually when they would be most relevant. Instead, we want to exclude them (via `BUNDLE_WITHOUT="development:test"`) in the Dockerfile so they apply to production by default, and then allow them locally with a `BUNDLE_WITHOUT=none`, which is a somewhat hacky way of saying "don't exclude any gem groups."
=> Update BUNDLE_WITHOUT groups in Dockerfile doc

assets/css/convox.css
Only tested in Chrome and Safari.
---
http://localhost/docs/overview/#the-convox-philosophy
http://localhost/docs/overview/#the-convox-philosophy
=> Prevent fixed header from overlapping anchors

_config/nginx.conf
We should either replace the `proxy_pass` entries with redirects (as proposed in this PR) or configure nginx to re-resolve them to avoid broken installer links when bin.equinox.io changes IPs.
We have two `proxy_pass` entries in `_config/nginx.conf`:
```
-location /install/osx.zip   { proxy_pass https://bin.equinox.io/c/jewmwFCp7w9/convox-stable-darwin-amd64.zip; }
-location /install/linux.zip { proxy_pass https://bin.equinox.io/c/jewmwFCp7w9/convox-stable-linux-amd64.zip; }
```
nginx resolves proxy_pass targets at boot and doesn't re-resolve them unless configured to do so. This stale DNS situation was the underlying cause of the inaccessibility of `https://convox.com/install/osx.zip` and `https://convox.com/install/linux.zip` today, because the target `bin.equinox.io` changed IPs.
From …
=> Replace /install/* proxy_pass with a 301 redirect

assets/css/convox.css
=> Reduce padding around code blocks. Make monospace black instead of red.

_resources/webhooks.md
Noticed that the example JSON payload included an `app:promote` action but the documented key is `release:promote`.
=> Update example promote action (app -> release)

_gen2/convox.yml.md
Apologies @ddollar, it looks like I missed a space in the markdown formatting and it messed up the formatting on the internal doc changes I made. Here is a fix. You can see the issue here: https://convox.com/docs/gen2/convox-yml/#internal
=> Fixing internal docs

_management/one-off-commands.md
Running a one-off command locally is the same as on a remote rack. Update the docs to reflect that.
=> Running local commands should use `run` not `start`
